config/routes.rb
Rails.application.routes.draw do

  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  root 'welcome#index'
  get 'welcome/index'
  
  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all


  get 'users/show'
  devise_for :users
  resources :users, only: [:show]

  get '/' => "boards#new"

  resources :boards, only: [:new, :create, :show, :destroy] do
    get 'share', on: :member
    get 'supporters', on: :member
    resource :invites, only: [:new, :create] do
      get 'claim'
    end
  end

  resources :tasks, only: [:create, :destroy, :edit, :update, :show] do
    post 'accept', on: :member
    post 'complete', on: :member
    post 'pin', on: :member
  end

  get 'twilio' => "messages#twilio_receive"

end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id                    :integer          not null, primary key
#  description           :string
#  start_time            :datetime
#  end_time              :datetime
#  task_type_id          :integer
#  board_id              :integer
#  shared                :boolean
#  accepted              :boolean
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  supporter_email       :string
#  supporter_message     :string
#  supporter_name        :string
#  title                 :string
#  user_id               :integer
#  completed             :boolean          default("false")
#  pinned                :boolean          default("false")
#  completion_check      :boolean          default("false")
#  completion_check_time :datetime
#

class Task < ActiveRecord::Base
  belongs_to :task_type
  belongs_to :board
  belongs_to :user
  validates_presence_of :completion_check_time, if: -> { self.completion_check }
  validates_presence_of :start_time
  validates_presence_of :task_type_id

  extend SimpleCalendar
  has_calendar attribute: :start_time

  default_scope -> { order('"pinned" DESC, start_time ASC') }
  scope :upcoming, -> { where("start_time > ?", Time.now).order('start_time ASC') }
  scope :not_taken, -> { where("accepted is null").order('start_time ASC') }

  def self.in_category(category)
    joins(:task_type).select do |t|
      t.task_type.category == category
    end
  end

  def accepted?
    user_id.present?
  end

  def complete!
    update_attributes(completed: true)
  end

  def pretty_start_time
    self.start_time.strftime("%B %d, %I:%M %p")
  end

  def pin!
    update_attributes(pinned: true)
  end

  def unpin!
    update_attributes(pinned: false)
  end

  def self.with_outstanding_completion_checks
    where(completion_check: true, completed: false).
    where("completion_check_time < ?", DateTime.now)
  end
end

app/models/task_type.rb
# == Schema Information
#
# Table name: task_types
#
#  id          :integer          not null, primary key
#  name        :string
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category    :string
#

class TaskType < ActiveRecord::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def create
    task = Task.new(params_with_datetimes(task_params))
    if task.valid?
      task.save
      flash[:notice] = "Task created successfully"
    else
      flash[:error] = "There was an error creating your task"
    end
    redirect_to board_path(task_params[:board_id])
  end

  def destroy
    task = Task.find(params[:id])
    id = task.board_id
    task.destroy
    redirect_to board_path(id)
  end

  def accept
    task = Task.find(params[:id])
    current_user.accept_task(task, task_params[:supporter_message])

    UserMailer.notify_supporter(task).deliver_now
    UserMailer.notify_board_owners(task).deliver_now

    flash[:notice] = "Thanks for signing up for the task!"
    redirect_to share_board_path(task.board_id)
  end

  def complete
    task = Task.find(params[:id])
    task.complete!
    redirect_to share_board_path(task.board_id)
    flash[:notice] = "Task has been marked as complete!"
    UserMailer.notify_owners_of_completion(task).deliver_now
  end

  def show
    @task = Task.find(params[:id])
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update_attributes(task_params)
    redirect_to board_path(@task.board)

    if @task.accepted?
      UserMailer.notify_supporter_of_edit(@task).deliver!
    end
  end

  def pin
    task = Task.find(params[:id])

    if task.pinned?
      task.unpin!
    else
      task.pin!
    end

    redirect_to task.board
  end

  private

  def task_params
    params.require(:task).permit(
      :description,
      :board_id,
      :task_type_id,
      :title,
      :supporter_email,
      :supporter_message,
      :supporter_name,
      :start_time,
      :start_date,
      :end_time,
      :pinned,
      :completed,
      :completion_check,
      :completion_check_time,
      :completion_check_date
    )
  end

  def create_date_time(date, time)
    begin
      DateTime.strptime("#{date} #{time}", "%m/%d/%Y %l:%M%p")
    rescue ArgumentError
      DateTime.now
    end
  end

  def params_with_datetimes(prms)
    unless prms[:start_date].blank? || prms[:start_time].blank?
      prms[:start_time] = create_date_time(prms[:start_date], prms[:start_time])
    end
    prms.delete(:start_date)

    if prms[:completion_check]
      unless prms[:completion_check_time].blank? || prms[:completion_check_date].blank?
        prms[:completion_check_time] = create_date_time(prms[:completion_check_date], prms[:completion_check_time])
      end
      prms.delete(:completion_check_date)
    end
    prms
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_available_task.html.erb
<div class="columns smasll-12 task-info unaccepted">
  <span class="task-type-name">
    <%= task.task_type.name %>
  </span>
  <% if task.pinned? %>
    <div class="label right success">Pinned</div>
  <% end %>

  <div class="primary-info">
    <span class="start-time">
      <p><strong>Description: </strong><%= task.description %></p>
      <strong>Start time: </strong><%= task.start_time.strftime("%B %d, %I:%M %p") %>
    </span>
    <a href="#" class="button default tiny right round" data-reveal-id="sign-up-modal-<%= task.id %>">
    More info
  </a>
  </div>

  <div id="sign-up-modal-<%= task.id %>" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
    <span class="task-type-name">
      <%= task.task_type.name %>
    </span>

    <div class="primary-info">
      <span class="start-time">
        <strong>Start time: </strong><%= task.start_time.strftime("%B %d, %I:%M %p") %>
        <p><strong>Name: </strong> <%= task.title %></p>
      </span>
    </div>

    <div class="other-info">
      <p><strong>Description:</strong> <%= task.description %></p>
    </div>

    <%= simple_form_for :task, { url: accept_task_path(task), method: :post } do |f| %>
      <%= f.input :supporter_message, { label: "Your note",
                                        placeholder: "Leave a note! Let the board owner you understand the task and show your support!",
                                        as: :text } %>
      <%= f.button :submit, "Sign up for this task", { class: "small" } %>
    <% end %>
  </div>
</div>

app/views/tasks/_edit_task.html.erb
<span class="right">
  <%= link_to fa_icon("times"), board_path(task.board_id) %>
</span>

<h4>Edit task:</h4>

<%= simple_form_for task, { url: task_path(task), method: :put } do |f| %>
  <%= f.input :title %>
  <%= f.input :description, as: :text %>

  <!-- START TIME? -->
 <div class="select-date-wrapper">
   <%= f.label(:start_time) %>
   <%= f.datetime_select :start_time, options = {order: [:month, :day, :year], discard_year: true, ampm: true, minute_step:15} %>
 </div>

  <!-- END TIME? -->
 <div class="select-date-wrapper">
   <%= f.label(:end_time) %>
   <%= f.datetime_select :end_time, options = {order: [:month, :day, :year], discard_year: true, ampm: true, minute_step:15} %>
 </div>

  <%= f.submit("Update task", class: "button center tiny radius add-task") %>
<% end %>

app/views/tasks/_form.html.erb
<div class="new-task-form">

  <%= simple_form_for :task, url: tasks_path, method: :post do |f| %>
    <h4> Add new task </h4>
    <%= f.input :task_type_id,
      collection: types,
      prompt: "Choose #{category} task",
      label: false,
      required: true %>

    <%= f.input :title, placeholder: "Title", label: false %>
    <%= f.input :description, as: :text, placeholder: "Description", label: false %>

    <!-- THIS IS TOO UGLY, FIX IT, something like below? -->
    <!-- f.input :start_time, as: :datetime -->
    <!-- f.input :end_time, as: :datetime -->

    <!-- START TIME? -->
    <div class="select-date-wrapper">
      <%= f.input :start_date, as: :string, input_html: { class: "date-picker", id: "#{category}-start-time" },
          label: false,
          placeholder: "Start Date" %>
      <%= f.input :start_time, as: :string, input_html: { class: "time-picker", id: "#{category}-start-time" },
          label: false,
          placeholder: "Start Time" %>
    </div>

    <%= f.input(:completion_check, as: :boolean, label: "Check that this task was completed via SMS?") %>
      <div class="select-date-wrapper completion-check-fields-wrapper">
        <%= f.input :completion_check_date, as: :string, input_html: { class: "date-picker", id: "#{category}-completion-time" },
            label: false,
            placeholder: "Date of check" %>
        <%= f.input :completion_check_time, as: :string, input_html: { class: "time-picker", id: "#{category}-completion-time" },
            label: false,
            placeholder: "Time of check" %>
      </div>
    <%= f.hidden_field :board_id, { value: @board.id } %>
    <%= f.submit("Add task", class: "button center radius add-task") %>
  <% end %>
</div>

app/views/tasks/_sidebar_list.html.erb
<div class="task-type-buttons content active" id="task-add-sidebar">
  <h5>Add a task:</h5>
  <% categories.each do |cat| %>
  <div>
    <a href="#" data-reveal-id="<%= "#{cat}-modal" %>">
      <div class="task-categories">
        <i class='<%=t cat%>'><%= ' ' + cat.titleize %></i>
      </div>
    </a>

    <div id="<%="#{cat}-modal"%>" class="reveal-modal tiny" data-reveal>
      <%= render partial: "tasks/form",
      locals: { category: cat, types: TaskType.where(category: cat.to_sym) } %>
      <a class="close-reveal-modal">&#215;</a>
    </div>
  </div>
  <% end %>

  </br>
  <h5>Other Actions:</h5>
  <div class="task-categories">
    <%= link_to "Invite Supporters", new_board_invites_path(@board) %>
  </div>
  <div class="task-categories">
    <%= link_to "View Supporters (#{@board.non_owners.count})", supporters_board_path(@board) %>
  </div>
</div>

app/views/tasks/_task.html.erb
<div class='<%= "columns large-12 task-info #{task.accepted? ? 'accepted' : 'available'} #{'completed' if task.completed}"  %>' id='<%= "task-#{task.id}"%>' >
  <div class="top-row">
    <span class="task-type-name">
      <%= fa_icon("user") if task.accepted? && !task.completed? %>
      <%= fa_icon("check-square-o") if task.completed? %>
      <%= "#{task.task_type.name}" %>
    </span>

    <ul class="button-group edit-buttons">
      <li>
        <%= link_to fa_icon("times"), task_path(task.id),
          method: "delete",
          id: 'delete-icon' %>
      </li>
      <% if task.pinned? %>
        <li>
          <%= link_to fa_icon("minus"), pin_task_path(task.id),
            method: "post",
            id: 'unpin-icon' %>
        </li>
      <% else %>
        <li>
          <%= link_to fa_icon("thumb-tack"), pin_task_path(task.id),
            method: "post",
            id: 'pin-icon' %>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="primary-info">
    <div class="title">
      <strong>Name: </strong><span><%= task.title %></span>
    </div>
    <div class="start-time">
      <strong>Start time: </strong><%= task.start_time.strftime("%B %d, %I:%M%p") %>
    </div>

    <div class="acceptance-info">
      <% if task.accepted? %>
       <strong>Accepted by:</strong> <%= task.user.friendly_name %>
      <% else %>
        <strong>Status: </strong><span>Available</span>
      <% end %>
      <div>
        <% if task.completed?  %>
          <strong>Status: </strong>Complete!</span>
        <% end %>
      </div>
    </div>
    <div class="other-info">
      <strong>Description:</strong> <%= task.description %>
        <% if task.accepted? %>
          <div class="supporter-note">
            <strong>Note: </strong> <em>"<%= task.supporter_message %>"</em>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/tasks/_user_task.html.erb
<div class="accepted-task task-info columns small-12">
  <span class="task-type-name">
    <%= fa_icon("check-square-o") if task.completed? %>
    <%= task.task_type.name %>
  </span>

  <% if task.completed? %>
    <span class="right button small success">Completed!</span>
  <% else %>
    <%= link_to "Mark as completed", complete_task_path(task),
    class: "button right small", method: :post %>
  <% end %>

  <div class="primary-info">
    <span class="start-time">
      <strong>To be done by: </strong><%= task.start_time.strftime("%B %d, %I:%M %p") %>
    </span>
  </div>

  <div class="other-info">
    <span><strong>Name:</strong> <%= task.title %></span></br>
    <span><strong>Description:</strong> <%= task.description %></span></br>
    <% if task.supporter_message.present? %>
      <span><strong>Your note: </strong> <%= task.supporter_message %></span></br>
    <% end %>
  </div>
</div>

app/views/tasks/edit.js.erb
$('#task-<%= @task.id %>').html(
  "<%= j(render('tasks/edit_task', task: @task)) %>"
);

app/views/tasks/show.html.erb
<div class= "container">
  <div class= "row">
    <%= render @task %>
  </div>
</div>