config/routes.rb
Rails.application.routes.draw do

  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  root 'welcome#index'
  get 'welcome/index'
  
  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all


  get 'users/show'
  devise_for :users
  resources :users, only: [:show]

  get '/' => "boards#new"

  resources :boards, only: [:new, :create, :show, :destroy] do
    get 'share', on: :member
    get 'supporters', on: :member
    resource :invites, only: [:new, :create] do
      get 'claim'
    end
  end

  resources :tasks, only: [:create, :destroy, :edit, :update, :show] do
    post 'accept', on: :member
    post 'complete', on: :member
    post 'pin', on: :member
  end

  get 'twilio' => "messages#twilio_receive"

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime
#  updated_at             :datetime
#  first_name             :string
#  last_name              :string
#  phone_number           :string
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :supporters
  has_many :tasks
  has_many :messages
  has_many :boards, through: :supporters
  before_validation { self.phone_number = sanitize_number(self.phone_number) if !self.phone_number.blank? }
  validates_format_of :phone_number, with: /\+1\d{10}/, if: -> { !self.phone_number.blank? }

  before_save { |user| user.email.downcase! }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email,
    presence: true,
    uniqueness: {
      case_sensitive: false
  }

  def add_board(board, owner=false)
    owner ||= false
    Supporter.create(user_id: id, board_id: board.id, owner: owner)
  end

  def owned_boards
    boards.includes(:supporters).where({ supporters: { owner: true } })
  end

  def supporting_boards
    boards.includes(:supporters).where({ supporters: { owner: false } })
  end

  def supporter_for(board)
    supporting_boards.any? { |b| b.id == board.id }
  end

  def accept_task(task, message=nil)
    task.update_attributes!({ user_id: id,
                              supporter_message: message
    })
  end

  def tasks_from_board(board)
    tasks.where({ board_id: board.id })
  end

  def friendly_name
    if self.first_name && self.last_name
      "#{self.first_name} #{self.last_name[0]}."
    end
  end

  def sanitize_number(number)
    return unless number
    number.gsub!(/[^\d\+]/,'')
    number = "+1" + number if number[0..1] != "+1"
    number
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    if current_user.id != params[:id].to_i
      flash['notice'] = "You don't have access to this page."
      redirect_to root_path
    end

    @own_boards = current_user.owned_boards
    @support_boards = current_user.supporting_boards
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div class="boards">
  <div class="row small-12 small-centered columns">
    <%= link_to new_board_path do %>
      <span class="label round success right add-board"><%= fa_icon("plus") %>Create a new board!</span>
    <% end %>

    <h3>Boards you own</h3>
    <% if !@own_boards.empty? %>

        <ul class="small-block-grid-4 board-list">
          <% @own_boards.each do |b| %>
            <li class="board-preview">
            <%= link_to b.name, b, class: "board-name" %>
              <a href="#" data-reveal-id="delete-board-modal-<%= b.id %>">
                <%= fa_icon("times", class: "right") %>
              </a>

              <p class="description"><em><%= b.description %></em></p>

              <div class="reveal-modal tiny" id="delete-board-modal-<%= b.id %>" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
                <h4>Delete this board and all of it's data?</h4>
                <a href="<%= board_path(b) %>" data-method="delete" class="center button round alert">Yes, delete board</a>
                <a class="close-reveal-modal" aria-label="Close">&#215;</a>
              </div>
            </li>
          <% end %>
        </ul>
    <% else %>
      <p>You are not currently the owner of any boards, create a board to get started!</p>

    <% end %>

    <h3>Boards you support</h3>
    <% if @support_boards.empty? %>
        <p>You are not currently a Supporter on any boards</p>
    <% else %>
      <% @support_boards.each do |b| %>
        <%= link_to b.name, share_board_path(b) %>
      <% end %>
    <% end%>

    <% if session[:code].present? %>
    <h3>Pending Board Invitations</h3>
      <% session[:code].each do |c| %>
        <% if inv = Invite.find_by(code: c) %>
          <%= link_to inv.board.name, claim_board_invites_path(board_id: inv.board, code:c) %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>