config/routes.rb
Rails.application.routes.draw do

  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  root 'welcome#index'
  get 'welcome/index'
  
  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all


  get 'users/show'
  devise_for :users
  resources :users, only: [:show]

  get '/' => "boards#new"

  resources :boards, only: [:new, :create, :show, :destroy] do
    get 'share', on: :member
    get 'supporters', on: :member
    resource :invites, only: [:new, :create] do
      get 'claim'
    end
  end

  resources :tasks, only: [:create, :destroy, :edit, :update, :show] do
    post 'accept', on: :member
    post 'complete', on: :member
    post 'pin', on: :member
  end

  get 'twilio' => "messages#twilio_receive"

end

app/views/layouts/_footer.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-58752024-1', 'herokuapp.com');
  ga('send', 'pageview');

</script>

app/views/layouts/_header.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <%=link_to (image_tag 'banner.png', size: '320'), root_path %>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <ul class="right">
      <li>
        <% if user_signed_in? %>
        <li><%= link_to current_user.email, user_path(current_user) %></li>
        <li><a href=<%= user_path(current_user) %> data-dropdown="drop" data-options="is_hover:true">My Boards</a></li>
        <ul id="drop" class="f-dropdown" data-dropdown-content>
          <% if user_signed_in? %>
          <% current_user.owned_boards.each do |b| %>
          <li><%= link_to b.name, board_path(b) %></li>
          <% end %>
          <% current_user.supporting_boards.each do |b| %>
          <li><%= link_to b.name, share_board_path(b) %></li>
          <% end %>
          <% end %>
        </ul>
        <li><%= link_to 'Create a Board', new_board_path %></li>
        <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
        <% else %>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
        <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </li>
    </ul>
  </section>
</nav>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<div class="row">
  <div class="large-4 large-offset-4 columns">
    <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= flash_helper name %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
    <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "SupportRoo" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.6.12/jquery.timepicker.js" %>
    <%= stylesheet_link_tag    "https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.6.12/jquery.timepicker.css" %>
    <%= render 'layouts/footer' %>
    <div id="fb-root"></div>
  </body>
</html>